inherit_from:
  - .rubocop_airbnb.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'config/routes.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
    - 'spec/**/*'
    - 'spec/factories/users.rb'
    - 'app/helpers/sessions_helper.rb'
    - 'app/controllers/password_resets_controller.rb'
