default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.db[:username] %>
  port: 3306
  host: '127.0.0.1'

test:
  <<: *default
  database: ci_test
